<div id="header">
    <nav class="menuBar">
        <a href="/"><div class="menuItem alignText_C">Home</div></a>
        <a href="/about"><div class="menuItem alignText_C">About Me</div></a>
        <a href="/projects"><div class="menuItem alignText_C">Projects</div></a>
        <a href="/music"><div class="menuItem alignText_C">Music</div></a>
        <a href="/quotes"><div class="menuItem alignText_C">Quotes</div></a>
    </nav>
</div>